apiVersion: argoproj.io/v1alpha1 # Changed from apps/v1
kind: Rollout # Changed from Deployment
metadata:
  name: hello-kubernetes
  labels: 
      name: hello-kubernetes
strategy:
    canary:
      analysis:
        templates:
        - templateName: webcheck
      args:
      - name: host
        value: hello-kubernetes
      steps:
      - setWeight: 20
      - pause:
          duration: "30s"
      - setWeight: 50
      - pause:
          duration: "30s"
