apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-kubernetes
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      analysis:
        templates:
        - templateName: webcheck
      canaryService: hello-kubernetes-canary-test 
      stableService: hello-kubernetes-stable-test
      trafficRouting:
        nginx:
          stableIngress: {{ .Values.ingress.name }}
      steps:
      - setWeight: 30
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 100
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 50
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
        - name: hello-kubernetes
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
             - name: MESSAGE
               value: Hey I just changed it successfully to mine
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcheck
spec:
  args:
  - name: hello-kubernetes
  metrics:
  - name: webcheck
    failureLimit: 1
    interval: "3"
    successCondition: result == "ok"
    provider:
      web:
        # paceholders are resolved when an AnalysisRun is created
        url: "http://{{args.host}}/"
        jsonPath: "{$.status}"