
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: hello-kubernetes.com
    http:
      paths:
      - path: /test
        backend:
          serviceName: {{ .Values.service.name1 }}
          servicePort: {{ .Values.service.port }}