apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcheck
spec:
  args:
  - name: hello-kubernetes-stg.com
  metrics:
  - name: webcheck
    failureLimit: 1
    interval: "3"
    successCondition: result == "ok"
    provider:
      web:
        # paceholders are resolved when an AnalysisRun is created
        url: "http://{{args.name}}/"
        jsonPath: "{$.status}"
