apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-kubernetes-stg
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      analysis:
        templates:
        - templateName: webcheck
        args:
        - name: host
          value: hello-kubernetes-stable-stg
      canaryService: hello-kubernetes-canary-stg 
      stableService: hello-kubernetes-stable-stg
      trafficRouting:
        nginx:
          stableIngress: {{ .Values.ingress.name }}
      steps:
      - setWeight: 30
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 100
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 50
  selector:
    matchLabels:
      app: hello-kubernetes-stg
  template:
    metadata:
      labels:
        app: hello-kubernetes-stg
    spec:
      containers:
        - name: hello-kubernetes-stg
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
             - name: MESSAGE
               value: Hey I just changed it successfully to stg
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcheck
spec:
  args:
  - name: host
  metrics:
  - name: webcheck
    failureLimit: 1
    successCondition: result == "ok"
    interval: 30s
    count: 5
    provider:
      web:
        # paceholders are resolved when an AnalysisRun is created
        url: http://hello-kubernetes-stg.com/
        jsonPath: "{$.status}"
