apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: hello-kubernetes-stg.com 
    http:
      paths:
      - path: 
        backend:
          serviceName: {{ .Values.service.name1 }} 
          servicePort: {{ .Values.service.port }}
    tls:
  - hosts:
    - hello-kubernetes-stg.com
    secretName: argocd-secret


#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: hello-kubernetes-stable-stg
#  annotations:
#    kubernetes.io/ingress.class: nginx
#spec:
#  rules:
#  - host: hello-kubernetes-stg.com 
#    http:
#      paths:
#      - backend:
#          serviceName: hello-kubernetes-stable-stg
#          servicePort: 80
