
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    namespace: ingress-basic
spec:
  rules:
  - host: hello-kubernetes-stg.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.service.name1 }} 
          servicePort: {{ .Values.service.port }}
