apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name1 }}
  annotations:
    app.access.url: nginx.extdns.ryaneschinger.com
spec:
  type: {{ .Values.service.type1 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name2 }}
spec:
  type: {{ .Values.service.type2 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}
