apiVersion: argoproj.io/v1alpha1 # Changed from apps/v1
kind: Rollout # Changed from Deployment
metadata:
  name: hello-kubernetes
  labels: 
      name: hello-kubernetes
spec:
  replicas: 8
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.9
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hey I just changed it successfully to mine
  strategy:
      canary:
        analysis:
          templates:
          - templateName: webcheck
        args:
        - name: host
          value: hello-kubernetes
        steps:
        - setWeight: 20
        - pause:
            duration: "30s"
        - setWeight: 50
        - pause:
            duration: "30s"
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcheck
spec:
  args:
  - name: host
  metrics:
  - name: webcheck
    failureLimit: 1
    interval: 5
    successCondition: result == "ok"
    provider:
      web:
        # paceholders are resolved when an AnalysisRun is created
        url: "http://{{args.host}}/"
        jsonPath: "{$.status}"
