apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-kubernetes-stable 
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: hello-kubernetes-canary
            port:
              number: 80
